---
abstract: 'Create an LWP UserAgent that records and plays back sessions'
author:
  - 'Edward Allen <ealleniii@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  LWPx::Record::DataSection: 0
  Module::Build: 0.3601
  Test::More: 0.88
  lib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-LWP-Recorder
no_index:
  directory:
    - inc
    - t
    - xt
    - examples
    - eg
provides:
  Test::LWP::Recorder:
    file: lib/Test/LWP/Recorder.pm
    version: v0.1.1
requires:
  Carp: 0
  Digest::MD5: 0
  File::Slurp: 0
  File::Spec: 0
  HTTP::Response: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
  List::Util: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-LWP-Recorder
  homepage: http://search.cpan.org/dist/Test-LWP-Recorder/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/riemann42/Test-LWP-Recorder.git
version: 0.1.1
x_BuiltWith:
  modules:
    Carp: 1.32
    Digest::MD5: 2.53
    File::Find: 1.20
    File::Slurp: 9999.19
    File::Spec: 3.40
    File::Temp: 0.22
    HTTP::Response: 6.01
    HTTP::Status: 6.00
    LWP::UserAgent: 6.03
    LWPx::Record::DataSection: 0.01
    List::Util: 1.32
    Module::Build: 0.4007
    Pod::Coverage::TrustPod: 0.100000
    Test::More: 0.98
    Test::Pod: 1.45
    Test::Pod::Coverage: 1.08
    base: 2.18
    lib: 0.63
    perl: 'NA(skipped: perl)'
    strict: 1.07
    warnings: 1.13
  perl:
    original: v5.16.3
    qv: 1
    version:
      - 5
      - 16
      - 3
  platform: linux
x_Dist_Zilla:
  perl:
    version: 5.016003
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@GitHub/GitHub::Meta'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@GitHub/GitHub::Update'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Prepender
      name: Prepender
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: CompileTests
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: CriticTests
      version: 1.111450
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: Test::Pod::LinkCheck
      version: 1.001
    -
      class: Dist::Zilla::Plugin::PodSpellingTests
      name: PodSpellingTests
      version: 1.112140
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.03
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 1.003
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: Bugtracker
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: Homepage
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 0
          show_uname: 0
      name: MetaData::BuiltWith
      version: 0.03000000
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: 0.18
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: MetaProvides::Package
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: DualBuilders
      version: 1.001
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: ReadmeFromPod
      version: 0.16
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: ChangelogFromGit
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Git::Commit
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: Clean
      version: 0.03
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: ArchiveRelease
      version: 4.00
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300038
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300038
x_authority: cpan:EALLENIII
